### ISSUE TITLE
Config loading doesn't properly merge default values and handle arrays

### ISSUE THREAD

**Issue by besynnerlig** [tnxqso/wave-flex-integrator#9]
From PR #6 by @zone11 :

If the example commands stored in commandsAfterLogin loaded from the defaultConfig.js are removed in the running application (e.g. no need for extra commands) and saved, they get overwritten by the default settings at the next start of the application.

This is just a temporary solution, the root cause is function loadConfig() comparing the the value array expecting the same number of keys as in defaultConfig.js

**Comment by besynnerlig** [comment]
This should be fixed by [4b556de](https://github.com/tnxqso/wave-flex-integrator/pull/8/commits/4b556de6f2ee439586f870c75f2712f9417f265f)

**Comment by zone11** [comment]
I'm sorry to tell you, but the problem persists.
Once I remove your DXcluster commands "SET/NAME JOHN, SET/SKIMMER CW, SET/SEEME" and save the config, the keys are remove from the config file. But when I start the application again, it gets overwritten as before and the configuration contains the settings above.

**Comment by besynnerlig** [comment]
Thanks! You are absolutely right about that. The thing is that I had fixed it but then I got another issue and I eventually fixed that issue to. But then as it appears the original issue came back. I will see if I can find out why it happens and next time I will test better! Thanks for contributing.

**Comment by besynnerlig** [comment]
I've fixed the issue once again in [70730b4](https://github.com/tnxqso/wave-flex-integrator/pull/18/commits/70730b4d8016ab4963d7a64a8c94a0a6414b9bba). I’m really hoping it works this time, it would be quite embarrassing if it doesn't! 😅

This was an extremely persistent bug, but persistence is key (and in this case, not the bug!). Thanks so much for your help in testing, really appreciate it. Let me know how it goes!

**Comment by zone11** [comment]
` If the stored array is intentionally shorter, we respect that` - so is it! 

Now it works as expected, thank you!
